# Generated by Django 4.1.4 on 2022-12-17 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='compleate',
            new_name='complete',
        ),
    ]
